name: "Changeset Release"
description: "A Github action for creating non-public releases with changesets"

branding:
  icon: octagon
  color: yellow

inputs:
  format:
    description: "The release tag format"
    required: false

outputs:
  tag:
    description: "The release tag"

runs:
  using: "node20"
  main: "dist/index.js"
