name: Release and Publish

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release

    permissions:
      contents: write

    outputs:
      tag: ${{ steps.release.outputs.tag }}

    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'changeset-release/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Release
        id: release
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish

    permissions:
      contents: write

    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Display Tag
        run: echo '${{ needs.release.outputs.tag }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.tag }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Publish
        uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: ${{ needs.release.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
